name: cssapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  flutter:
    sdk: flutter
  convex_bottom_bar: ^3.1.0+1
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  lottie: ^1.2.1
  flip_card: ^0.6.0
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  fade_shimmer: ^2.2.0
  flutter_widget_from_html: ^0.9.1
  carousel_slider: ^4.2.1
  sn_progress_dialog: ^1.0.9
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  syncfusion_flutter_pdfviewer: ^20.4.43
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.2

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background/
    - assets/images/CSS_logo/
    - assets/images/event_thumbnails/
    - assets/images/events/abacus/
    - assets/images/events/esperanza/
    - assets/images/framers/
    - assets/lottie/
    - assets/

  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Cormorant Unicase
      fonts:
        - asset: assets/fonts/CormorantUnicase-Regular.ttf
    - family: EastSeaDokdo
      fonts:
        - asset: assets/fonts/EastSeaDokdo-Regular.ttf
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Regular.ttf
    - family: Segoe Font
      fonts:
        - asset: assets/fonts/segoe-font/segoesc.ttf
